import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { userService } from '../../services/api';
import '../Dashboard.css';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const UserManagement = () => {
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState('User Control');
  const [searchQuery, setSearchQuery] = useState('');
  const [users, setUsers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [editingId, setEditingId] = useState(null);
  const [editData, setEditData] = useState({});
  const [newUser, setNewUser] = useState({
    username: '',
    email: '',
    password: '',
    accountType: 'Student',
    mobile: '',
    idNumber: ''
  });
  const [user, setUser] = useState(null);

  // Fetch users
  useEffect(() => {
    const fetchUsers = async () => {
      try {
        const userData = JSON.parse(localStorage.getItem('user'));
        if (!userData) {
          navigate('/signin');
          return;
        }
        setUser(userData);
        const response = await userService.getAllUsers();
        setUsers(response.users);
        setLoading(false);
      } catch (err) {
        setError(err.message || 'Failed to fetch users');
        setLoading(false);
      }
    };

    fetchUsers();
  }, [navigate]);

  const handleEdit = (user) => {
    setEditingId(user._id);
    setEditData({ ...user });
  };

  const handleEditChange = (e) => {
    const { name, value } = e.target;
    setEditData((prev) => ({
      ...prev,
      [name]: value
    }));
  };

  const handleNewUserChange = (e) => {
    const { name, value } = e.target;
    setNewUser((prevUser) => ({
      ...prevUser,
      [name]: value,
    }));
  };

  const handleSave = async () => {
    try {
      await userService.updateUser(editingId, editData);
      setUsers(users.map(user => 
        user._id === editingId ? { ...editData } : user
      ));
      setEditingId(null);
    } catch (err) {
      setError(err.message || 'Failed to update user');
    }
  };

  const handleDelete = async (userId) => {
    try {
      await userService.deleteUser(userId);
      setUsers(users.filter(user => user._id !== userId));
    } catch (err) {
      setError(err.message || 'Failed to delete user');
    }
  };

  const handleAddUser = async (e) => {
    e.preventDefault();
    try {
      const response = await userService.createUser(newUser);
      setUsers([...users, response.user]);
      setNewUser({
        username: '',
        email: '',
        password: '',
        accountType: 'Student',
        mobile: '',
        idNumber: ''
      });
      setActiveTab('User Control');
    } catch (err) {
      setError(err.message || 'Failed to create user');
    }
  };

  const generatePDF = () => {
    // Create new PDF instance
    const doc = new jsPDF();
    
    // Add logo
    const logoUrl = require('../../assets/logo-acadamiPlan.png');
    doc.addImage(logoUrl, 'PNG', 20, 15, 35, 20);
    
    // Report title and company info
    doc.setFontSize(18);
    doc.setTextColor(40, 40, 40);
    doc.text('User Management Report', 105, 20, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text('AcademiPlan Solutions', 105, 30, { align: 'center' });
    doc.text('Mo 34/60, Wijerama Road, Colombo 07', 105, 35, { align: 'center' });
    doc.text('Phone: 0764456789 | Email: info@academiplan.com', 105, 40, { align: 'center' });
    
    // Date and generated by
    const today = new Date();
    doc.text(`Generated on: ${today.toLocaleDateString()}`, 15, 45);
    doc.text(`Generated by: ${user?.username} (${user?.accountType})`, 15, 50);
    
    // Summary statistics
    doc.setFontSize(12);
    doc.text('Summary Statistics', 15, 65);
    
    doc.setFontSize(10);
    doc.text(`Total Users: ${users.length}`, 15, 75);
    
    const userTypes = ['Student', 'Lecturer', 'Administrative'];
    userTypes.forEach((type, index) => {
      const count = users.filter(u => u.accountType === type).length;
      doc.text(`${type}s: ${count} (${Math.round((count / users.length) * 100)}%)`, 15, 80 + (index * 5));
    });
    
    // Add table for each user type
    userTypes.forEach((type, typeIndex) => {
      const typeUsers = users.filter(u => u.accountType === type);
      
      if (typeUsers.length > 0) {
        if (typeIndex > 0) doc.addPage();
        
        doc.setFontSize(14);
        doc.text(`${type} Users`, 60, 70);
        
        autoTable(doc, {
          startY: typeIndex === 0 ? 100 : 25,
          head: [['ID', 'Username', 'Email', 'Mobile', 'ID Number', 'Created At']],
          body: typeUsers.map(user => [
            user._id.substring(0, 8),
            user.username,
            user.email,
            user.mobile || 'N/A',
            user.idNumber || 'N/A',
            new Date(user.createdAt).toLocaleDateString()
          ]),
          theme: 'grid',
          headStyles: {
            fillColor: typeIndex === 0 ? [41, 128, 185] : 
                      typeIndex === 1 ? [58, 166, 95] : 
                      [156, 39, 176],
            textColor: 255,
            fontStyle: 'bold'
          },
          alternateRowStyles: {
            fillColor: [245, 245, 245]
          },
          styles: {
            fontSize: 8,
            cellPadding: 2,
            overflow: 'linebreak'
          },
          columnStyles: {
            0: { cellWidth: 20 },
            1: { cellWidth: 30 },
            2: { cellWidth: 40 },
            3: { cellWidth: 25 },
            4: { cellWidth: 25 },
            5: { cellWidth: 25 }
          }
        });
      }
    });
    
    // Footer with page numbers
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.setTextColor(150, 150, 150);
      doc.text(
        `Page ${i} of ${pageCount}`,
        doc.internal.pageSize.width / 2,
        doc.internal.pageSize.height - 10,
        { align: 'center' }
      );
    }
    
    doc.save(`User_Management_Report_${new Date().toISOString().slice(0,10)}.pdf`);
  };

  const filteredUsers = users.filter(user => {
    const query = searchQuery.toLowerCase();
    return (
      user.username.toLowerCase().includes(query) ||
      user.email.toLowerCase().includes(query) ||
      user.accountType.toLowerCase().includes(query) ||
      (user.mobile && user.mobile.includes(query)) ||
      (user.idNumber && user.idNumber.includes(query))
    );
  });

  const userTypes = ['Student', 'Lecturer', 'Administrative'];

  if (loading) return <div>Loading users...</div>;
  if (error) return <div className="error-message">{error}</div>;

  return (
    <div className="dashboard-container">
      {/* Sidebar */}
      <div className="sidebar">
        <div className="logo">
          <img 
            src={require('../../assets/compani-logo1.png')} 
            alt="AcademiPlan Logo" 
            className="logo-image"
          />
        </div>
        <nav>
          <ul>
            {['User Control', 'Add New User'].map((item) => (
              <li 
                key={item} 
                className={activeTab === item ? 'active' : ''}
                onClick={() => setActiveTab(item)}
              >
                {item}
              </li>
            ))}
          </ul>
        </nav>
      </div>

      {/* Main */}
      <div className="main-content">
        <header className="header">
          <h2 className="h2">User Management</h2>
          <div className="search-container">
            <input 
              type="text" 
              placeholder="Search users..." 
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
            />
          </div>
          <div className="user-info">
            <button className="signout-btn" onClick={() => {
              localStorage.removeItem('user');
              navigate('/signin');
            }}>
              Signout
            </button>
            <div className="profile-pic">
              {user?.username?.charAt(0).toUpperCase()}
            </div>
            <div className="user-details">
              <span className="greeting">Hello {user?.username}</span>
              <span className="user-role">{user?.accountType}</span>
            </div>
          </div>
        </header>

        {/* Main Section */}
        {activeTab === 'Add New User' ? (
          <div className="user-form">
            <h3>Add New User</h3>
            {error && <div className="error-message">{error}</div>}
            <form onSubmit={handleAddUser}>
              <div className="form-row">
                <label>Username:</label>
                <input type="text" name="username" value={newUser.username} onChange={handleNewUserChange} required />
              </div>
              <div className="form-row">
                <label>Email:</label>
                <input type="email" name="email" value={newUser.email} onChange={handleNewUserChange} required />
              </div>
              <div className="form-row">
                <label>Password:</label>
                <input type="password" name="password" value={newUser.password} onChange={handleNewUserChange} required />
              </div>
              <div className="form-row">
                <label>Account Type:</label>
                <select name="accountType" value={newUser.accountType} onChange={handleNewUserChange}>
                  {userTypes.map(type => (
                    <option key={type} value={type}>{type}</option>
                  ))}
                </select>
              </div>
              <div className="form-row">
                <label>Mobile:</label>
                <input type="tel" name="mobile" value={newUser.mobile} onChange={handleNewUserChange} pattern="[0-9]{10}" required />
              </div>
              <div className="form-row">
                <label>ID Number:</label>
                <input type="text" name="idNumber" value={newUser.idNumber} onChange={handleNewUserChange} required />
              </div>
              <button type="submit" className="add-user-btn">Add User</button>
            </form>
          </div>
        ) : (
          <div className="conflicts-table">
            <div className="table-header">
              <h3>User List</h3>
              <button className="pdf-btn" onClick={generatePDF}>Generate PDF Report</button>
            </div>
            {userTypes.map(type => (
              <div key={type} className="user-table-section">
                <h4>{type}s ({filteredUsers.filter(u => u.accountType === type).length})</h4>
                <table>
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Username</th>
                      <th>Email</th>
                      <th>Mobile</th>
                      <th>ID Number</th>
                      <th>Created At</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {filteredUsers
                      .filter(user => user.accountType === type)
                      .map(user => (
                        <tr key={user._id}>
                          <td>{user._id.substring(0, 8)}</td>
                          <td>{editingId === user._id ? <input name="username" value={editData.username} onChange={handleEditChange} /> : user.username}</td>
                          <td>{editingId === user._id ? <input name="email" value={editData.email} onChange={handleEditChange} /> : user.email}</td>
                          <td>{editingId === user._id ? <input name="mobile" value={editData.mobile} onChange={handleEditChange} /> : user.mobile}</td>
                          <td>{user.idNumber}</td>
                          <td>{new Date(user.createdAt).toLocaleDateString()}</td>
                          <td>
                            {editingId === user._id ? (
                              <>
                                <button className="save-btn" onClick={handleSave}>💾 Save</button>
                                <button className="cancel-btn" onClick={() => setEditingId(null)}>❌ Cancel</button>
                              </>
                            ) : (
                              <>
                                <button className="edit-btn" onClick={() => handleEdit(user)}>✏️ Edit</button>
                                <button className="delete-btn" onClick={() => handleDelete(user._id)}>🗑️ Delete</button>
                              </>
                            )}
                          </td>
                        </tr>
                      ))}
                  </tbody>
                </table>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default UserManagement;