import React, { useState, useEffect } from 'react';
import { Pie, Bar } from 'react-chartjs-2';
import { Chart as ChartJS, ArcElement, Tooltip, Legend, CategoryScale, LinearScale, BarElement } from 'chart.js';
import './Dashboard.css';
import { Link, useNavigate } from 'react-router-dom';
import axios from 'axios';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

ChartJS.register(ArcElement, Tooltip, Legend, CategoryScale, LinearScale, BarElement);

const Dashboard = () => {
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState('Dashboard');
  const [searchQuery, setSearchQuery] = useState('');
  const [user, setUser] = useState(null);
  const [searchError, setSearchError] = useState('');
  const [conflicts, setConflicts] = useState([]);
  const [courses, setCourses] = useState([]);
  const [enrollments, setEnrollments] = useState([]);
  const [loading, setLoading] = useState(true);
  const [stats, setStats] = useState({
    totalConflicts: 0,
    resolvedConflicts: 0,
    pendingConflicts: 0,
    totalCourses: 0,
    totalEnrollments: 0
  });

  useEffect(() => {
    const userData = JSON.parse(localStorage.getItem('user'));
    if (!userData) {
      navigate('/signin');
      return;
    }
    setUser(userData);
    fetchDashboardData();
  }, [navigate]);

  const fetchDashboardData = async () => {
    try {
      setLoading(true);
      
      // Fetch conflicts
      const conflictsRes = await axios.get('http://localhost:5000/api/timetable/conflicts');
      setConflicts(conflictsRes.data);
      
      // Fetch courses
      const coursesRes = await axios.get('http://localhost:5000/api/courses');
      setCourses(coursesRes.data);
      
      // Fetch enrollments
      const enrollmentsRes = await axios.get('http://localhost:5000/api/enrollments');
      setEnrollments(enrollmentsRes.data);
      
      // Calculate stats
      const totalConflicts = conflictsRes.data.length;
      const resolvedConflicts = conflictsRes.data.filter(c => c.status === 'resolved').length;
      
      setStats({
        totalConflicts,
        resolvedConflicts,
        pendingConflicts: totalConflicts - resolvedConflicts,
        totalCourses: coursesRes.data.length,
        totalEnrollments: enrollmentsRes.data.length
      });
      
    } catch (error) {
      console.error('Error fetching dashboard data:', error);
    } finally {
      setLoading(false);
    }
  };

  const resolveConflict = async (conflictId) => {
    try {
      await axios.post(`http://localhost:5000/api/timetable/conflicts/${conflictId}/resolve`);
      fetchDashboardData(); // Refresh data
    } catch (error) {
      console.error('Error resolving conflict:', error);
    }
  };

  const generatePDFReport = () => {
    // Create new jsPDF instance
    const doc = new jsPDF();
    
    // Add logo
    const logoUrl = require('../assets/logo-acadamiPlan.png');
    doc.addImage(logoUrl, 'PNG', 20, 15, 35, 20);
    
    // Report title and company info
    doc.setFontSize(18);
    doc.setTextColor(40, 40, 40);
    doc.text('Dashboard Summary Report', 105, 20, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text('AcademiPlan Solutions', 105, 30, { align: 'center' });
    doc.text('Mo 34/60, Wijerama Road, Colombo 07', 105, 35, { align: 'center' });
    doc.text('Phone: 0764456789 | Email: info@academiplan.com', 105, 40, { align: 'center' });
    
    // Date and generated by
    const today = new Date();
    doc.text(`Generated on: ${today.toLocaleDateString()}`, 15, 45);
    doc.text(`Generated by: ${user?.username} (${user?.accountType})`, 15, 50);
    
    // Add summary statistics
    doc.setFontSize(14);
    doc.setTextColor(40, 40, 40);
    doc.text('System Overview', 15, 65);
    
    doc.setFontSize(10);
    doc.text(`Total Conflicts: ${stats.totalConflicts}`, 15, 75);
    doc.text(`Resolved Conflicts: ${stats.resolvedConflicts} (${Math.round((stats.resolvedConflicts / stats.totalConflicts) * 100)}%)`, 15, 80);
    doc.text(`Pending Conflicts: ${stats.pendingConflicts}`, 15, 85);
    doc.text(`Total Courses: ${stats.totalCourses}`, 15, 90);
    doc.text(`Total Enrollments: ${stats.totalEnrollments}`, 15, 95);
    
    // Add conflicts table
    doc.setFontSize(14);
    doc.text('Recent Conflicts', 15, 110);
    
    const conflictHeaders = [
      'ID', 
      'Course', 
      'Code', 
      'Lecturer', 
      'Hall', 
      'Time', 
      'Status'
    ];
    
    const conflictData = conflicts.slice(0, 10).map(conflict => [
      `#${conflict._id?.substring(0, 6)}`,
      conflict.timetableEntry?.courseName || 'N/A',
      conflict.timetableEntry?.courseCode || 'N/A',
      conflict.timetableEntry?.lecturer || 'N/A',
      conflict.timetableEntry?.lectureHall || 'N/A',
      `${conflict.timetableEntry?.day || 'N/A'}, ${conflict.timetableEntry?.timeSlot || 'N/A'}`,
      conflict.status === 'resolved' ? 'Resolved' : 'Pending'
    ]);
    
    autoTable(doc, {
      startY: 115,
      head: [conflictHeaders],
      body: conflictData,
      theme: 'grid',
      headStyles: {
        fillColor: [41, 128, 185],
        textColor: 255,
        fontStyle: 'bold'
      },
      alternateRowStyles: {
        fillColor: [245, 245, 245]
      },
      margin: { top: 115 },
      styles: {
        fontSize: 8,
        cellPadding: 2,
        overflow: 'linebreak'
      }
    });
    
    // Add courses table
    doc.addPage();
    doc.setFontSize(14);
    doc.text('Course Overview', 15, 20);
    
    const courseHeaders = [
      'Code',
      'Name',
      'Enrollments',
      'Lecturer',
      'Credits'
    ];
    
    const courseData = courses.slice(0, 15).map(course => [
      course.code,
      course.name,
      enrollments.filter(e => e.courseId === course._id).length,
      course.lecturer || 'N/A',
      course.credits || 'N/A'
    ]);
    
    autoTable(doc, {
      startY: 25,
      head: [courseHeaders],
      body: courseData,
      theme: 'grid',
      headStyles: {
        fillColor: [58, 166, 95],
        textColor: 255,
        fontStyle: 'bold'
      },
      alternateRowStyles: {
        fillColor: [245, 245, 245]
      },
      styles: {
        fontSize: 8,
        cellPadding: 2,
        overflow: 'linebreak'
      }
    });
    
    // Add charts to the PDF
    const canvasPie = document.getElementById('pie-chart');
    const canvasBar = document.getElementById('bar-chart');
    
    if (canvasPie) {
      const pieImage = canvasPie.toDataURL('image/png');
      doc.addPage();
      doc.setFontSize(14);
      doc.text('Conflict Status Distribution', 105, 20, { align: 'center' });
      doc.addImage(pieImage, 'PNG', 50, 30, 110, 110);
    }
    
    if (canvasBar) {
      const barImage = canvasBar.toDataURL('image/png');
      doc.addPage();
      doc.setFontSize(14);
      doc.text('Top Courses by Enrollment', 105, 20, { align: 'center' });
      doc.addImage(barImage, 'PNG', 30, 30, 150, 110);
    }
    
    // Footer with page numbers
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.setTextColor(150, 150, 150);
      doc.text(
        `Page ${i} of ${pageCount}`,
        doc.internal.pageSize.width / 2,
        doc.internal.pageSize.height - 10,
        { align: 'center' }
      );
    }
    
    doc.save(`Dashboard_Report_${new Date().toISOString().slice(0,10)}.pdf`);
  };

  useEffect(() => {
    if (searchQuery.trim() === '') {
      setSearchError('');
      return;
    }

    if (searchQuery.length < 3) {
      setSearchError('Search term must be at least 3 characters');
      return;
    } else {
      setSearchError('');
    }
  }, [searchQuery]);

  const handleTabClick = (tab) => {
    setActiveTab(tab);
  };

  const handleSignOut = () => {
    localStorage.removeItem('user');
    navigate('/signin');
  };

  const handleSearchChange = (e) => {
    setSearchQuery(e.target.value);
  };

  // Prepare chart data
  const pieData = {
    labels: ['Pending', 'Resolved'],
    datasets: [{
      data: [stats.pendingConflicts, stats.resolvedConflicts],
      backgroundColor: ['#f93a2b', '#2ee112'],
    }],
  };

  const barData = {
    labels: courses.slice(0, 5).map(course => course.code),
    datasets: [{
      label: 'Enrollments',
      data: courses.slice(0, 5).map(course => 
        enrollments.filter(e => e.courseId === course._id).length
      ),
      backgroundColor: '#3498db',
    }],
  };

  if (loading) {
    return <div className="dashboard-container loading">Loading dashboard...</div>;
  }

  return (
    <div className="dashboard-container">
      {/* Left Sidebar */}
      <div className="sidebar">
        <div className="logo">
          <img 
            src={require('../assets/compani-logo1.png')} 
            alt="AcademiPlan Logo" 
            className="logo-image"
          />
        </div>
        <nav>
          <ul>
            {['Dashboard', 'Conflict Resolution', 'Real Time Notifications', 'Course Enrollment', 'User Management'].map((item) => (
              <li 
                key={item} 
                className={activeTab === item ? 'active' : ''}
                onClick={() => handleTabClick(item)}
              >
                <Link to={`/${item.toLowerCase().replace(/\s+/g, '-')}`} style={{ textDecoration: 'none', color: 'inherit' }}>
                  {item}
                </Link>
              </li>
            ))}
          </ul>
        </nav>
      </div>

      {/* Main Content */}
      <div className="main-content">
        {/* Top Header */}
        <header className="header">
          <h2 className='h2'>Dashboard</h2>
          <div className="search-container">
            <svg className="search-icon" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <circle cx="11" cy="11" r="8"></circle>
              <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
            </svg>
            <input 
              type="text" 
              placeholder="Type here to search..." 
              value={searchQuery}
              onChange={handleSearchChange}
              className={searchError ? 'error' : ''}
            />
            {searchError && <span className="search-error">{searchError}</span>}
          </div>
          <div className="user-info">
            <button className="signout-btn" onClick={handleSignOut}>
              Signout
            </button>
            {user?.profilePhoto ? (
              <img 
                src={`http://localhost:5000${user.profilePhoto}`} 
                alt="Profile" 
                className="profile-pic"
                onError={(e) => {
                  e.target.onerror = null;
                  e.target.src = 'default-profile.png';
                }}
              />
            ) : (
              <div className="profile-pic">
                {user?.username?.charAt(0).toUpperCase()}
              </div>
            )}
            <div className="user-details">
              <span className="greeting">Hello {user?.username}</span>
              <span className="user-role">{user?.accountType}</span>
            </div>
          </div>
        </header>

        {/* Content Sections */}
        <div className="content-sections">
          {/* Conflict Distribution Section */}
          <section className="conflict-distribution">
            <h2>Conflict Overview</h2>
            <div className="charts-container">
              <div className="chart-card">
                <Pie data={pieData} id="pie-chart" />
                <div className="chart-title">Conflict Status</div>
              </div>
              <div className="stats-card">
                <div className="stat-item">
                  <div className="stat-label">Total Conflicts</div>
                  <div className="stat-value">{stats.totalConflicts}</div>
                </div>
                <div className="stat-item">
                  <div className="stat-label">Resolved</div>
                  <div className="stat-value">{stats.resolvedConflicts}</div>
                </div>
                <div className="stat-item">
                  <div className="stat-label">Pending</div>
                  <div className="stat-value">{stats.pendingConflicts}</div>
                </div>
              </div>
            </div>
          </section>

          {/* Courses and Enrollments Section */}
          <section className="Different-Courses">
            <h2>Courses & Enrollments</h2>
            <div className="charts-container">
              <div className="chart-card">
                <div className="chart-wrapper">
                  <Bar 
                    data={barData}
                    id="bar-chart"
                    options={{
                      maintainAspectRatio: false,
                      responsive: true
                    }}
                  />
                </div>
                <div className="chart-title">Top Courses by Enrollment</div>
              </div>
              <div className="stats-card">
                <div className="stat-item">
                  <div className="stat-label">Total Courses</div>
                  <div className="stat-value">{stats.totalCourses}</div>
                </div>
                <div className="stat-item">
                  <div className="stat-label">Total Enrollments</div>
                  <div className="stat-value">{stats.totalEnrollments}</div>
                </div>
              </div>
            </div>
          </section>

          {/* Right Side Section */}
          <section className="right-section">
            {/* Recent Conflicts */}
            <div className="conflicts-card">
              <h3>Recent Conflicts</h3>
              {conflicts.slice(0, 3).map(conflict => (
                <div key={conflict._id} className="conflict-item">
                  <div className="conflict-course">{conflict.timetableEntry?.courseName || 'N/A'}</div>
                  <div className="conflict-time">
                    {conflict.timetableEntry?.day || 'N/A'}, {conflict.timetableEntry?.timeSlot || 'N/A'}
                  </div>
                  <div className={`conflict-status ${conflict.status}`}>
                    {conflict.status}
                  </div>
                  {conflict.status === 'pending' && (
                    <button 
                      className="resolve-btn"
                      onClick={() => resolveConflict(conflict._id)}
                    >
                      Resolve
                    </button>
                  )}
                </div>
              ))}
              {conflicts.length === 0 && (
                <div className="no-conflicts">No conflicts found</div>
              )}
            </div>

            {/* Quick Actions */}
            <div className="actions-card">
              <h3>Quick Actions</h3>
              <button 
                className="action-btn primary"
                onClick={() => navigate('/course-enrollment')}
              >
                <i className="fas fa-user-plus"></i> Add Enrollment
              </button>
              <button 
                className="action-btn success"
                onClick={generatePDFReport}
              >
                <i className="fas fa-file-pdf"></i> Generate Report
              </button>
              {user?.accountType === 'admin' && (
                <button 
                  className="action-btn warning"
                  onClick={() => navigate('/user-management')}
                >
                  <i className="fas fa-users-cog"></i> Manage Users
                </button>
              )}
            </div>

            {/* Search Results */}
            {searchQuery && (
              <div className="search-results-card">
                <h3>Search Results</h3>
                {courses.filter(course => 
                  course.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
                  course.code.toLowerCase().includes(searchQuery.toLowerCase())
                ).map(course => (
                  <div key={course._id} className="search-result-item">
                    {course.code} - {course.name}
                  </div>
                ))}
              </div>
            )}
          </section>
        </div>
      </div>
    </div>
  );
};

export default Dashboard;